// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TH01.Data;

#nullable disable

namespace TH01.Migrations
{
    [DbContext(typeof(CoffeeshopDbContext))]
    [Migration("20250529011936_Detail")]
    partial class Detail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TH01.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Americano là một shot espresso pha với nước nóng. Nó thường được pha trong một cốc 6 ounce và gồm một nửa espresso và một nửa nước nóng, hoặc ⅓ espresso và ⅔ nước nóng.\n Thông thường mọi người sẽ uống nước, sau đó thêm espresso lên trên, \n vì nó giữ được lớp crema, là lớp bọt màu nâu đỏ, nhưng cũng có thể làm ngược lại.",
                            ImageUrl = "https://insanelygoodrecipes.com/wp-content/uploads/2020/07/Cup-Of-Creamy-Coffee-1024x536.webp",
                            IsTrendingProduct = false,
                            Name = "America",
                            Price = 25m
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Trung Nguyen Legend is a Vietnamese business group engaged in coffee production, processing, and distribution. It is known as the largest domestic coffee brand in Vietnam, exporting products to over 60 countries, including major markets such as G7 countries, the United States,\n the European Union, the United Kingdom, Germany, China, Canada, Russia, Japan, Dubai, and ASEAN. When talking about quality Vietnamese coffee,\n this brand with its aromatic and robust coffee cannot be overlooked",
                            ImageUrl = "https://bna.1cdn.vn/2025/02/02/cdnphoto.dantri.com.vn-i7ew_jatefe35zxjrpzbe0euvlk-thumb_w-1020-2022-08-06-_caphe-1659747941762.jpeg",
                            IsTrendingProduct = false,
                            Name = "Vietnam",
                            Price = 20m
                        },
                        new
                        {
                            Id = 3,
                            Detail = "In the UK, coffee preferences are varied but a\n few stand out as particularly popular. While many enjoy flat whites\n, cappuccinos, and lattes, the most popular coffee drink in the UK is the flat white",
                            ImageUrl = "https://images2.thanhnien.vn/528068263637045248/2023/9/8/cafefqxn-16941744457661231106144.jpg",
                            IsTrendingProduct = false,
                            Name = "United Kingdom",
                            Price = 15m
                        },
                        new
                        {
                            Id = 4,
                            Detail = "Indian Mysore coffee is a market name for high-quality wet processed (washed)\n coffees from the southern region in the state of Karnataka. The coffee is known for its subtle,\n rich flavor complemented by a medium to full body and moderate though distinct acidity.",
                            ImageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2024/10/16/ca-phe-1-17290637850462076395892.jpg",
                            IsTrendingProduct = false,
                            Name = "India",
                            Price = 15m
                        },
                        new
                        {
                            Id = 5,
                            Detail = "Raf coffee (Russian: раф-кофе) is a popular coffee drink in some countries of the former USSR,\n which appeared in the late 1990s in Russia. Prepared by adding cream and vanilla sugar to a single shot of espresso and\n then foaming the mix with a steam heater.",
                            ImageUrl = "https://simexcodl.com.vn/wp-content/uploads/2023/11/cac-loai-ca-phe-o-viet-nam-8.jpg",
                            IsTrendingProduct = false,
                            Name = "Russian",
                            Price = 25m
                        },
                        new
                        {
                            Id = 6,
                            Detail = "This refers to regular black coffee. It is usually served in small portions as an espresso or French press coffee.\n The French enjoy café noir with meals or as a pick-me-up in the afternoon.",
                            ImageUrl = "https://file.hstatic.net/1000274203/article/ca_phe_robusta_va_arabica_loai_nao_ngon_09d00c9c4e76439786c981c7a8c43cd0.jpg",
                            IsTrendingProduct = false,
                            Name = "France",
                            Price = 35m
                        });
                });

            modelBuilder.Entity("TH01.Models.ShoppingcartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("TH01.Models.ShoppingcartItem", b =>
                {
                    b.HasOne("TH01.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
